uri: http://rubyforge.org
username: pluginaweek
is_private: false
rubyforge:
  group_ids:
    pluginaweek: 2608
  package_ids:
    table_helper: 
  type_ids:
    .zip: 3000
    .tgz: 5000
    .gem: 1400
  processor_ids:
    Any: 8000